//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendancePooling
    {
        public int PollingId { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<System.TimeSpan> AttTime { get; set; }
        public Nullable<int> InOutTypeId { get; set; }
    }
}
