//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceLogMaster
    {
        public decimal ID { get; set; }
        public string AcNo { get; set; }
        public System.DateTime CheckTime { get; set; }
        public byte IsProcessed { get; set; }
        public int MachineNo { get; set; }
        public int InOutTypeId { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<int> VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public string Memoinfo { get; set; }
        public string sn { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> ReasonID { get; set; }
        public string UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public Nullable<bool> isApp { get; set; }
    }
}
