//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpExperienceDetail
    {
        public long EmpId { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public long PKId { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public string EditedOn { get; set; }
    
        public virtual EmpMaster EmpMaster { get; set; }
    }
}
