//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpScheduleDetail
    {
        public long DID { get; set; }
        public long MID { get; set; }
        public System.DateTime AttDate { get; set; }
        public string AttDay { get; set; }
        public Nullable<long> ShiftID { get; set; }
    
        public virtual EmpScheduleMaster EmpScheduleMaster { get; set; }
    }
}
