//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDeduction
    {
        public int id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> AttendanceTypeId { get; set; }
        public Nullable<double> NbrOfDays { get; set; }
        public Nullable<System.DateTime> DeductionDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<int> NoofLate { get; set; }
        public Nullable<int> NoofHalfDay { get; set; }
        public Nullable<int> CurrentMonth { get; set; }
        public Nullable<int> CurrentYear { get; set; }
    }
}
