//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftMaster()
        {
            this.ShiftScheduleGeneralDetails = new HashSet<ShiftScheduleGeneralDetail>();
        }
    
        public int ShiftId { get; set; }
        public string ShiftDesc { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<System.TimeSpan> ActualIn { get; set; }
        public Nullable<System.TimeSpan> ActualOut { get; set; }
        public bool IsHalfDayApplicable { get; set; }
        public Nullable<System.TimeSpan> HalfDay { get; set; }
        public bool IsNightShift { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.TimeSpan> MaxTimeout { get; set; }
        public Nullable<System.TimeSpan> AbsentTime { get; set; }
        public Nullable<System.TimeSpan> ShiftOverTimeStart { get; set; }
        public Nullable<System.TimeSpan> ShiftOverTimeEnd { get; set; }
        public bool IsOverTimeApplicable { get; set; }
        public Nullable<bool> Is24HourShift { get; set; }
        public string ShiftColor { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftScheduleGeneralDetail> ShiftScheduleGeneralDetails { get; set; }
    }
}
