//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IncomeTaxMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_IncomeTaxMaster()
        {
            this.tbl_IncomeTaxPosting = new HashSet<tbl_IncomeTaxPosting>();
        }
    
        public int Id { get; set; }
        public Nullable<double> SalaryStartSlab { get; set; }
        public Nullable<double> SalaryEndSlab { get; set; }
        public Nullable<double> Tax_Percentage { get; set; }
        public Nullable<double> ExtraAmount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public string EditedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IncomeTaxPosting> tbl_IncomeTaxPosting { get; set; }
    }
}
