//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Manager()
        {
            this.tbl_PendingRequestDetail = new HashSet<tbl_PendingRequestDetail>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public long ManagerID { get; set; }
        public int LevelID { get; set; }
        public int DepartmentID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        public virtual EmpMaster EmpMaster { get; set; }
        public virtual tbl_ManagerLevel tbl_ManagerLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PendingRequestDetail> tbl_PendingRequestDetail { get; set; }
    }
}
