//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProvidentFundMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ProvidentFundMaster()
        {
            this.tbl_AllocatedProvidentFund = new HashSet<tbl_AllocatedProvidentFund>();
            this.tbl_ProvidentFundPosting = new HashSet<tbl_ProvidentFundPosting>();
        }
    
        public int Id { get; set; }
        public string ProvidentFundName { get; set; }
        public Nullable<int> ValueTypeId { get; set; }
        public Nullable<double> ProvidentFundValue { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AllocatedProvidentFund> tbl_AllocatedProvidentFund { get; set; }
        public virtual tbl_DecConCategory tbl_DecConCategory { get; set; }
        public virtual ValueType ValueType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProvidentFundPosting> tbl_ProvidentFundPosting { get; set; }
    }
}
