//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LoanMaster()
        {
            this.tbl_LoanDetail = new HashSet<tbl_LoanDetail>();
        }
    
        public int LoanId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<System.DateTime> LoanStartDate { get; set; }
        public Nullable<System.DateTime> LoanMaturityDate { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public bool IsDeleted { get; set; }
        public string LoanDesc { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual EmpMaster EmpMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanDetail> tbl_LoanDetail { get; set; }
    }
}
