//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notifications
    {
        public long ID { get; set; }
        public long NotifyFor { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsSeen { get; set; }
        public string NotificationDetail { get; set; }
        public string NotificationLink { get; set; }
        public string NotificationTitle { get; set; }
        public long CreatedByID { get; set; }
        public bool IsAdminRequest { get; set; }
        public string SeenDateTime { get; set; }
    }
}
