//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PendingRequestDetail
    {
        public long DID { get; set; }
        public long MID { get; set; }
        public long tblManager_ID { get; set; }
        public int HLevel { get; set; }
        public bool ApprovedByThisManager { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsRejected { get; set; }
        public bool IsCancelByUser { get; set; }
    
        public virtual tbl_Manager tbl_Manager { get; set; }
        public virtual tbl_PendingRequestMaster tbl_PendingRequestMaster { get; set; }
    }
}
