//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllocatedLatePolicies
    {
        public int AllocatedLatePolicyId { get; set; }
        public int LatePolicyId { get; set; }
        public long EmpId { get; set; }
        public System.DateTime LatePolicyStartDate { get; set; }
        public Nullable<System.DateTime> LatePolicyEndDate { get; set; }
    
        public virtual EmpMaster EmpMaster { get; set; }
        public virtual tbl_LatePolicyMaster tbl_LatePolicyMaster { get; set; }
    }
}
