//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reports
    {
        public int ID { get; set; }
        public string ReportsName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual tbl_ReportCategory tbl_ReportCategory { get; set; }
    }
}
