//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDO_TimeAttandance_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValueType()
        {
            this.tbl_EOBIMaster = new HashSet<tbl_EOBIMaster>();
            this.tbl_ProvidentFundMaster = new HashSet<tbl_ProvidentFundMaster>();
            this.tbl_TaxMaster = new HashSet<tbl_TaxMaster>();
            this.tbl_SecurityDepositMaster = new HashSet<tbl_SecurityDepositMaster>();
        }
    
        public int ValueTypeId { get; set; }
        public string ValueTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EOBIMaster> tbl_EOBIMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProvidentFundMaster> tbl_ProvidentFundMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TaxMaster> tbl_TaxMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SecurityDepositMaster> tbl_SecurityDepositMaster { get; set; }
    }
}
