//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_FullAndFinalSettlement
    {
        public int Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<double> EOBI { get; set; }
        public Nullable<double> ProvidentFund { get; set; }
        public Nullable<double> Advance { get; set; }
        public Nullable<double> Loan { get; set; }
        public Nullable<double> LastMonthSalary { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> PFWithdrawl { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreateBy { get; set; }
    
        public virtual EmpMaster EmpMaster { get; set; }
    }
}
