//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpScheduleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpScheduleMaster()
        {
            this.EmpScheduleDetails = new HashSet<EmpScheduleDetail>();
        }
    
        public long ID { get; set; }
        public int GeneralSchedulePKId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long EmpId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    
        public virtual EmpMaster EmpMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpScheduleDetail> EmpScheduleDetails { get; set; }
        public virtual EmpScheduleMaster EmpScheduleMaster1 { get; set; }
        public virtual EmpScheduleMaster EmpScheduleMaster2 { get; set; }
        public virtual ShiftScheduleGeneralMaster ShiftScheduleGeneralMaster { get; set; }
    }
}
