//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
