//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveMapDetail
    {
        public long DID { get; set; }
        public long MID { get; set; }
        public long LeaveID { get; set; }
        public double LeaveAllowed { get; set; }
    
        public virtual LeaveMapMaster LeaveMapMaster { get; set; }
    }
}
