//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftScheduleGeneralDetail
    {
        public int DID { get; set; }
        public System.DateTime AttDate { get; set; }
        public string AttDay { get; set; }
        public bool IsHoliday { get; set; }
        public string HolidayType { get; set; }
        public int MID { get; set; }
        public int ShiftID { get; set; }
        public string BarColor { get; set; }
        public string Remarks { get; set; }
    
        public virtual ShiftMaster ShiftMaster { get; set; }
        public virtual ShiftScheduleGeneralMaster ShiftScheduleGeneralMaster { get; set; }
    }
}
