//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SecurityDepositMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SecurityDepositMaster()
        {
            this.tbl_AllocatedSecurityDeposit = new HashSet<tbl_AllocatedSecurityDeposit>();
            this.tbl_SecurityDepositPosting = new HashSet<tbl_SecurityDepositPosting>();
        }
    
        public int SecurityDepositId { get; set; }
        public string DepositName { get; set; }
        public Nullable<int> ValueTypeId { get; set; }
        public Nullable<double> DepositValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AllocatedSecurityDeposit> tbl_AllocatedSecurityDeposit { get; set; }
        public virtual ValueType ValueType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SecurityDepositPosting> tbl_SecurityDepositPosting { get; set; }
    }
}
