//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveDeduction
    {
        public long ID { get; set; }
        public Nullable<long> Empid { get; set; }
        public Nullable<int> LeaveID { get; set; }
        public Nullable<double> DeductDays { get; set; }
        public Nullable<System.DateTime> DeductionDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
    
        public virtual LeaveSetup LeaveSetup { get; set; }
    }
}
