//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IconControl
    {
        public int ID { get; set; }
        public string Dashboard { get; set; }
        public string Login { get; set; }
        public string Report { get; set; }
        public string Title { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
