//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalaryPostingMaster
    {
        public long SalaryPostingId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<int> MonthNo { get; set; }
        public Nullable<int> YearNo { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> TillDate { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<double> PerDaySalary { get; set; }
        public Nullable<double> PerHourSalary { get; set; }
        public string TotalOT { get; set; }
        public Nullable<double> OTAmount { get; set; }
        public Nullable<int> TotalAbsent { get; set; }
        public Nullable<double> AbsentAmount { get; set; }
        public Nullable<int> TotalLeave { get; set; }
        public Nullable<double> LeaveAmount { get; set; }
        public Nullable<double> LateAmount { get; set; }
        public Nullable<int> TotalLate { get; set; }
        public Nullable<int> TotalHalfDay { get; set; }
        public Nullable<double> HalfDayAmount { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public Nullable<double> AdvanceAmount { get; set; }
        public string HolidayOT { get; set; }
        public Nullable<double> HolidayOTAmount { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<double> PolicyLateDeduction { get; set; }
    
        public virtual EmpMaster EmpMaster { get; set; }
    }
}
