//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllocatedDeductions
    {
        public int AllocatedDeductionId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<int> DeductionId { get; set; }
        public Nullable<System.DateTime> DeductionMonth { get; set; }
    
        public virtual DeductionMaster DeductionMaster { get; set; }
        public virtual EmpMaster EmpMaster { get; set; }
    }
}
