//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AutoEmailDetail
    {
        public int ID { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public Nullable<System.TimeSpan> EmailTime { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual tbl_AutoEmailTypes tbl_AutoEmailTypes { get; set; }
    }
}
