//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpLateDetails
    {
        public long Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<int> DeductId { get; set; }
        public Nullable<double> Deduct_Amount { get; set; }
        public Nullable<bool> IsExempt { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
    }
}
