//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanDetail
    {
        public long LoanDetailId { get; set; }
        public Nullable<System.DateTime> LoanInstallmentDate { get; set; }
        public Nullable<int> LoanId { get; set; }
        public Nullable<int> LoanStatusId { get; set; }
        public Nullable<double> InstallmentAmount { get; set; }
    
        public virtual tbl_LoanMaster tbl_LoanMaster { get; set; }
        public virtual tbl_LoanStatusMaster tbl_LoanStatusMaster { get; set; }
    }
}
