//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpLateDeduct
    {
        public long Id { get; set; }
        public Nullable<int> Late_DeductId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> MonthNo { get; set; }
        public Nullable<int> YearNo { get; set; }
    }
}
