//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReason
    {
        public long ID { get; set; }
        public string Reason { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDated { get; set; }
    }
}
